version: '3.7'
services:
  jenkins:
    build: .
    privileged: true
    user: root
    ports:
      - 80:8080
      - 50000:50000
    container_name: jenkins
    volumes:
      - /home/ubuntu/environment/datos/jenkins:/var/jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/local/bin/docker:/usr/local/bin/docker
      - /usr/bin/docker:/usr/bin/docker
